### ISSUE TITLE
Run FFMPEG minimized or hiden

### ISSUE THREAD

**Issue by djs45** [slhck/ffmpeg-progress-yield#3]
Hello
Is there a way to run ffmpeg with your library in hiden or minimized ?
Many thanks

**Comment by djs45** [comment]
And is there a way to retrieve statut error @ end of compression ?
Thanks a lot

**Comment by slhck** [comment]
As I am not a Windows user, it will be hard for me to test these changes. I prefer to not use `shell=True` since it requires passing the whole command as a string that is correctly formatted/escaped.  Also, it works differently under Windows and Unix-based systems—this would make it incompatible.

I remember a previous issue with `universal_newlines=True` that also didn't work under Windows.

If you have a platform-indepdendent suggestion as to how to fix it, please propose a PR. Otherwise I am not sure at this point how to solve it.

**Comment by djs45** [comment]
Yo have to remove '**' in     def run_command_with_progress : 

    def run_command_with_progress(self, popen_kwargs={}) -> Generator[int, None, None]:

**Comment by slhck** [comment]
Sorry, I don't understand. The current definition of that function has no `**`:

https://github.com/slhck/ffmpeg-progress-yield/blob/dcde02184ca2faf63a24eafd87a8f0845f037dfc/ffmpeg_progress_yield/ffmpeg_progress_yield.py#L49

**Comment by djs45** [comment]
effectively.

I d'ont understand why It work now but it work

Congrat et thank you !
