### ISSUE TITLE
How to stop a running ffmpeg process?

### ISSUE THREAD

**Issue by Akascape** [slhck/ffmpeg-progress-yield#4]
Hi, @slhck 
I want to stop a running ffmpeg process but don't know how to do it?
I tried `process.run_command_with_progress(popen_kwargs="q")` but it's not working.
I want to give the "Q" command in the running ffmpeg process so that it can safely quit the conversion.

**Comment by slhck** [comment]
There are basically three ways to stop the process:

1. Pass a `-t` option to the output arguments to make it stop automatically
2. Send 'q' to the program stdin
3. Send a `SIGINT` or `SIGTERM` signal to the running process

Only the first is currently possible. There is a pipe for stdin but you cannot pass anything to it since it is not exposed. I think I can write a small wrapper in the API for that.

**Comment by slhck** [comment]
You now have a `.quit()` method. For example:

```python
ff = FfmpegProgress(cmd)
for progress in ff.run_command_with_progress():
    if progress > 50:
        ff.quit()
        break
```

In principle you can also now access the `process` member directly, allowing you to manipulate the called subprocess even more, but I think this should suffice.
